

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import ClientWrapper from "./ClientWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


//建立全域
export default function RootLayout({children,}:Readonly<{children: React.ReactNode;}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
      <ClientWrapper>{children}</ClientWrapper>
      </body>
    </html>
  );
}



